# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  usersserviceapi:
    image: usersserviceapi
    build:
      context: .
      dockerfile: eCommers.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 4000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_HOST=postgres-container
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=eCommersUsers
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

    networks:
      - users-postgres-network
      - ecommerce-network
    depends_on:
      - postgres-container
  
  postgres-container:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      - users-postgres-network

  productsserviceapi:
    image: sohelpateldotnet/ecommerce-products-microservices:v1.0
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=mysql-container
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_DATABASE=ecommerceproductsdatabase
      - MYSQL_PORT=3306
    ports:
      - "4001:8080"
    networks:
      - products-mysql-network
      - ecommerce-network
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - ../ProductService/mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - products-mysql-network
  
  orderserviceapi:
    image: sohelpateldotnet/ecommerce-orders-microservice:v1.0
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_HOST=mongodb-container
      - MONGO_PORT=27017
      - MONGO_DATABASE=OrdersDatabase
      - UsersMicroserviceName=usersserviceapi
      - UsersMicroservicePort=4000
    ports:
      - 4002:8080
    networks:
      - orders-mongo-network
      - ecommerce-network
    depends_on:
      - mongodb-container

  mongodb-container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ../eCommers.OrderService/mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - orders-mongo-network
    
networks:
  users-postgres-network:
    driver: bridge
  products-mysql-network:
    driver: bridge
  orders-mongo-network:
    driver: bridge
  ecommerce-network:
    driver: bridge
  